// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Mon May 16 10:20:07 2022

control control_inst
(
	.Opcode(Opcode_sig) ,	// input [5:0] Opcode_sig
	.CLK(CLK_sig) ,	// input  CLK_sig
	.Reset(Reset_sig) ,	// input  Reset_sig
	.PCSrc(PCSrc_sig) ,	// output [1:0] PCSrc_sig
	.MemAddr(MemAddr_sig) ,	// output [1:0] MemAddr_sig
	.MemData(MemData_sig) ,	// output [0:0] MemData_sig
	.MemRead(MemRead_sig) ,	// output [0:0] MemRead_sig
	.MemWrite(MemWrite_sig) ,	// output [0:0] MemWrite_sig
	.SPWrite(SPWrite_sig) ,	// output [0:0] SPWrite_sig
	.ACCSrc(ACCSrc_sig) ,	// output [2:0] ACCSrc_sig
	.ACCWrite(ACCWrite_sig) ,	// output [0:0] ACCWrite_sig
	.ALUSrcA(ALUSrcA_sig) ,	// output [1:0] ALUSrcA_sig
	.ALUSrcB(ALUSrcB_sig) ,	// output [2:0] ALUSrcB_sig
	.Zero(Zero_sig) ,	// output [1:0] Zero_sig
	.ALUOp(ALUOp_sig) ,	// output [1:0] ALUOp_sig
	.BneOrBeq(BneOrBeq_sig) ,	// output [1:0] BneOrBeq_sig
	.PCWrite(PCWrite_sig) ,	// output [1:0] PCWrite_sig
	.Branch(Branch_sig) ,	// output [1:0] Branch_sig
	.IRWrite(IRWrite_sig) 	// output [0:0] IRWrite_sig
);

defparam control_inst.Fetch = 0;
defparam control_inst.Decode = 1;
defparam control_inst.Load = 2;
defparam control_inst.Addi = 3;
defparam control_inst.Save = 4;
defparam control_inst.Loadi = 5;
defparam control_inst.Jal = 6;
defparam control_inst.Ori = 7;
defparam control_inst.And = 8;
defparam control_inst.Slt = 9;
defparam control_inst.SwOrLw = 10;
defparam control_inst.Lw = 11;
defparam control_inst.Sw = 12;
defparam control_inst.Or = 13;
defparam control_inst.Beq = 14;
defparam control_inst.Sub = 15;
defparam control_inst.Bne = 16;
defparam control_inst.Jump = 17;
defparam control_inst.Ms = 18;
defparam control_inst.Add = 19;
defparam control_inst.Slti = 20;
defparam control_inst.Loadui = 21;
