// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Mon May 16 10:41:50 2022

memory memory_inst
(
	.data(data_sig) ,	// input [DATA_WIDTH-1:0] data_sig
	.addr(addr_sig) ,	// input [ADDR_WIDTH-1:0] addr_sig
	.we(we_sig) ,	// input  we_sig
	.clk(clk_sig) ,	// input  clk_sig
	.q(q_sig) 	// output [DATA_WIDTH-1:0] q_sig
);

defparam memory_inst.DATA_WIDTH = 16;
defparam memory_inst.ADDR_WIDTH = 10;
