// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Tue May 17 10:46:23 2022

mux2b16 mux2b16_inst
(
	.A(A_sig) ,	// input [15:0] A_sig
	.B(B_sig) ,	// input [15:0] B_sig
	.C(C_sig) ,	// input [15:0] C_sig
	.D(D_sig) ,	// input [15:0] D_sig
	.OP(OP_sig) ,	// input [1:0] OP_sig
	.Out(Out_sig) 	// output [15:0] Out_sig
);

